export enum Routes {
  AUTH = 'auth',
  USER = 'user',
  EMAIL = 'email',
  PROFILE = 'profile',
}

export enum Services {
  AUTH = 'AUTH_SERVICE',
  USER = 'USER_SERVICE',
  PRISMA = 'PRISMA_SERVICE',
  EMAIL = 'EMAIL_SERVICE',
  PASSWORD = 'PASSWORD_SERVICE',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION_SERVICE',
  JWT_TOKEN = 'JWT_TOKEN_SERVICE',
  OTP = 'OTP_SERVICE',
  POST = 'POST_SERVICE',
  LIKE = 'LIKE_SERVICE',
  REPOST = 'REPOST_SERVICE',
  MENTION = 'MENTION_SERVICE',
  PROFILE = 'PROFILE_SERVICE',
  USERS = 'USERS_SERVICE',
  REDIS = 'REDIS_SERVICE',
}

export enum RequestType {
  WEB = 'WEB',
  MOBILE = 'MOBILE',
}
