openapi: 3.0.3
info:
  title: X Clone API
  version: 1.0.0
  description: API documentation for social interactions (follow, block, mute, and direct messages)

servers:
  - url: https://api.example.com

components:
  schemas:
    PaginationMetadata:
      type: object
      properties:
        totalItems:
          type: integer
          description: Total number of items available.
          example: 1
        page:
          type: integer
          description: The current page number.
          example: 1
        perPage:
          type: integer
          description: Number of items per page.
          example: 10
        totalPages:
          type: integer
          description: Total number of pages.
          example: 1

paths:
  /users/{id}/follow:
    post:
      summary: Follow a user
      description: Follow a user by their ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the user to follow
          schema:
            type: string
      responses:
        200:
          description: Successfully followed the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: success }
                  data:
                    type: object
                    properties:
                      followingId: { type: string, example: "12345" }
                      followerId: { type: string, example: "67890" }
                      followedAt: { type: string, format: date-time, example: "2025-10-17T10:00:00Z" }
        400:
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: fail }
                  message: { type: string, example: Cannot follow yourself }

    delete:
      summary: Unfollow a user
      description: Unfollow a user by their ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the user to unfollow
          schema:
            type: string
      responses:
        200:
          description: Successfully unfollowed user
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: success }
                  data:
                    type: object
                    properties:
                      unfollowedId: { type: string, example: "12345" }
        400:
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: fail }
                  message: { type: string, example: User was not being followed }

  /users/{id}/followers:
    get:
      summary: Get followers list
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        200:
          description: List of followers
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: success }
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        userId: { type: string, example: "67890" }
                        username: { type: string, example: "omar" }
                        displayName: { type: string, example: "Omar Nabil" }
                        profileImageURL: { type: string, example: "https://example.com/profiles/omar.jpg" }
                        bio: { type: string, example: "Tech enthusiast and blogger." }
                        followedAt: { type: string, format: date-time }
                  metadata:
                    $ref: '#/components/schemas/PaginationMetadata'
        400:
          description: Invalid user ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: fail }
                  message: { type: string, example: User not found }

  /users/{id}/following:
    get:
      summary: Get following list
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        200:
          description: List of users the given user is following
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: success }
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        userId: { type: string, example: "12345" }
                        username: { type: string, example: "dev_ahmed" }
                        displayName: { type: string, example: "Ahmed Mostafa" }
                        profileImageURL: { type: string, example: "https://example.com/profiles/ahmed.jpg" }
                        bio: { type: string, example: "Frontend developer" }
                        followedAt: { type: string, format: date-time }
                  metadata:
                    $ref: '#/components/schemas/PaginationMetadata'
        400:
          description: Invalid user ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: fail }
                  message: { type: string, example: User not found }

  /users/{id}/block:
    post:
      summary: Block a user
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        200:
          description: Successfully blocked the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: success }
                  data:
                    type: object
                    properties:
                      blockedId: { type: string, example: "12345" }
                      blockedAt: { type: string, format: date-time }
        400:
          description: Cannot block yourself
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: fail }
                  message: { type: string, example: Cannot block yourself }

    delete:
      summary: Unblock a user
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        200:
          description: Successfully unblocked user
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: success }
                  data:
                    type: object
                    properties:
                      unblockedId: { type: string, example: "12345" }
        400:
          description: User not blocked
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: fail }
                  message: { type: string, example: User was not blocked }

  /users/blocks:
    get:
      summary: Get list of blocked users
      responses:
        200:
          description: List of blocked users
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: success }
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        userId: { type: string, example: "12345" }
                        username: { type: string, example: "troll_user" }
                        displayName: { type: string, example: "Annoying Guy" }
                        profileImageURL: { type: string, example: "https://example.com/profiles/troll.jpg" }
                        bio: { type: string, example: "Spams replies." }
                        blockedAt: { type: string, format: date-time }
                  metadata:
                    $ref: '#/components/schemas/PaginationMetadata'
        400:
          description: Request error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: fail }
                  message: { type: string, example: Could not fetch blocked users }

  /users/{id}/mute:
    post:
      summary: Mute a user
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        200:
          description: User muted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: success }
                  data:
                    type: object
                    properties:
                      mutedId: { type: string, example: "98765" }
                      mutedAt: { type: string, format: date-time }
        400:
          description: Cannot mute yourself
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: fail }
                  message: { type: string, example: Cannot mute yourself }

    delete:
      summary: Unmute a user
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        200:
          description: Successfully unmuted
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: success }
                  data:
                    type: object
                    properties:
                      unmutedId: { type: string, example: "98765" }
        400:
          description: User not muted
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: fail }
                  message: { type: string, example: User was not muted }

  /users/muted:
    get:
      summary: Get list of muted users
      responses:
        200:
          description: Muted users list
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: success }
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        userId: { type: string, example: "98765" }
                        username: { type: string, example: "noisy_user" }
                        profileImageURL: { type: string, example: "https://example.com/profiles/noisy.jpg" }
                        bio: { type: string, example: "Tech enthusiast and blogger." }
                        mutedAt: { type: string, format: date-time }
                  metadata:
                    $ref: '#/components/schemas/PaginationMetadata'
        400:
          description: Request error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: fail }
                  message: { type: string, example: Could not fetch muted users }

  /messages:
    get:
      summary: Get messages from a conversation
      parameters:
        - name: conversationId
          in: query
          required: true
          schema: { type: string }
      responses:
        200:
          description: List of messages
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: success }
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        messageId: { type: string }
                        senderId: { type: string }
                        text: { type: string }
                        sentAt: { type: string, format: date-time }
                  metadata:
                    $ref: '#/components/schemas/PaginationMetadata'
        400:
          description: Invalid conversation ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: fail }
                  message: { type: string, example: Conversation not found }

    post:
      summary: Send a new message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                conversationId: { type: string, example: "12345" }
                text: { type: string, example: "Hey, how’s it going?" }
      responses:
        201:
          description: Message sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: success }
                  data:
                    type: object
                    properties:
                      messageId: { type: string }
                      senderId: { type: string }
                      text: { type: string }
                      sentAt: { type: string, format: date-time }
        400:
          description: Failed to send message
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: fail }
                  message: { type: string, example: Message could not be sent }

  /conversations:
    get:
      summary: Get list of conversations
      responses:
        200:
          description: List of conversations
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: success }
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        conversationId: { type: string }
                        user:
                          type: object
                          properties:
                            id: { type: string }
                            username: { type: string }
                            displayName: { type: string }
                            profileImageURL: { type: string }
                        lastMessage: { type: string }
                        updatedAt: { type: string, format: date-time }
                  metadata:
                    $ref: '#/components/schemas/PaginationMetadata'
        400:
          description: Failed to fetch conversations
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: fail }
                  message: { type: string, example: Could not retrieve conversations }

  /conversations/unseen:
    get:
      summary: Get number of unseen conversations
      responses:
        200:
          description: Number of unseen conversations
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: success }
                  data:
                    type: object
                    properties:
                      unseenCount: { type: integer, example: 3 }
        400:
          description: Request error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: fail }
                  message: { type: string, example: Could not fetch unseen count }
